AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
  RoleArn:
    Type: String
  SourceBucket: 
    Type: String
  TargetBucket:
    Type: String
Resources:
  LambdaOutboundCopy:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !Ref RoleArn
      FunctionName: 'dev-myoutbound'
      Handler: index.handler
      Environment:
        Variables:
          SrcBucket:
            Ref: SourceBucket
          DestBucket:
            Ref: TargetBucket      
      Code:
        ZipFile: !Sub |
          exports.handler = async function(event, context) {
            console.log('Event received: \n')
            //console.log('Environment variable. TargetBucket: ' + process.env.DestBucket)
            return context.logStreamName;
          }
      Tags:
        - Key: "env"
          Value: !Ref EnvironmentName
        - Key: "resource-owner"
          Value: "cj"
  LambdaTrigger:
    Type: Custom::LambdaTrigger
    Properties:
      FunctionName: !Ref LambdaOutboundCopy
      BucketName: !Ref SourceBucket
